Update 9. Triangle Path Sum.cpp
shumbul/21-Days-DSA-Challenge pull request #14
Opened 2023-12-29 08:56 UTC by dhanwalkarjay

2023-12-29 19:02 UTC, shumbul requested changes
Please change file name to 9. Triangle Path Sum-
dhanwalkarjay.cpp so it doesn't overwrite the exisiting file.

2023-12-30 09:19 UTC, dhanwalkarjay commented
I change file name to 9. Triangle Path Sum-dhanwalkarjay.cpp now check it.

2023-12-31 12:57 UTC, shumbul commented
> I change file name to 9. Triangle Path Sum-dhanwalkarjay.cpp now check it.

You have changed the PR title, not the file name. Please check once.

2024-01-03 07:57 UTC, shumbul approved these changes

2024-01-03 07:57 UTC, merged